### ISSUE TITLE
System.ApplicationException: "音声ファイルの保存"は起動していません

### ISSUE THREAD

**Issue by trejkaz** [saga-dash/VoiceroidEx#1]
試しに音声ファイルを出力させようとしたら、こういうエラーが発生しました。

```
C:\V\VoiceroidEx.v1.6.1>VoiceroidEx "test" "C:\V\VoiceroidEx.v1.6.1\test"
---setTalkText---
setText: test
-----------------
---SaveVoice---
hOpenSaveWindowButton: 31B30
System.ApplicationException: "音声ファイルの保存"は起動していません
   at saga.util.WindowHandleSearch.Update()
   at saga.voiceroid.VoiceroidNotify4Win7.SaveVoiceImpl(String pathStr)
   at saga.voiceroid.VoiceroidEx.Main(String[] args)
エラーが発生しました
何かキーを押してください
```

ですが、「音声ファイルの保存」は起動しています：

<img width="588" alt="snip 3" src="https://cloud.githubusercontent.com/assets/43236/9835259/312a09ee-5a25-11e5-8c41-8ce45f08b275.PNG">

環境：
- VoiceroidEx 1.6.1
- VOICEROID+ 唯月ゆかり 1.5.1
- Windows 10
- .NET Framework 3.5

Windowsとか.NETはあまり慣れていないからこれ以上調べる方法も分かりません。

**Comment by trejkaz** [comment]
今日の検査結果：

P/Invoke メソッドの定義には CharSet = CharSet.Auto が必要みたいですね。

これだけを直したら、保存ダイアログを見つけます。

ですが次の問題、保存ボタンをクリックしない。（エラーメッセージも出ない）

上のスクリーンショットにはそのボタンは英語だから試しに日本語に変えたけどそれでもダメです。
コード調べたらボタンのテキストは関係なくインデックスで見つけるからおそらく、Windows 10 の保存ダイアログにはインデックスが違うかなと思います。

<img width="583" alt="snip2 2" src="https://cloud.githubusercontent.com/assets/43236/9835271/eccf2f12-5a25-11e5-8e7f-fc2068681fe8.PNG">

**Comment by trejkaz** [comment]
ここですね：

            public static VoiceroidInfo CreateYukari()
            {
                return new VoiceroidInfo(VoiceroidType.Yukari, SystemType.Type1, "VOICEROID＋ 結月ゆかり",
                    "音声ファイルの保存", 180, -1, 9, 7, 35, 3, 19);
            }

この19を**21**に変えたら保存できます。
全VOICEROIDは同じく19ですね。
つまり、SaveButtonIndexはVOICEROIDのバージョンじゃなくてWindowsのバージョンによって違います。

**Comment by tomoki** [comment]
自分も同じ問題に当たって、ビルドし直しました。
@trejkaz さんの修正で動いています。
ただ、自分でビルドするのも面倒なので、この問題に対して$15の懸賞金をかけました。

I want this issue to be solved, so I added bounty on this issue.
https://www.bountysource.com/issues/26635401-system-applicationexception

**Comment by saga-dash** [comment]
対応が遅くなり申し訳ありませんでした。通知が全く来ず、Githubにログインしてもレポジトリに入るまで表示されないので気づきませんでした。

@trejkaz さんの仰るとおりダイアログ系はOSver依存ですので修正し、[tag:1.6.3](https://github.com/saga-dash/VoiceroidEx/releases/tag/1.6.3)にて公開しました。
